### ISSUE TITLE
Set the profile of the glasses like in "Magic VR Player" in SIDE-by-SIDE feature

### ISSUE THREAD

**Issue by PhilippeLC92** [Consti10/myMediaCodecPlayer-for-FPV#1]
Hello,
Congratulations for your android application that allows to view video stream with udp protocol without latency. 
Now I'm working on the telemetry text overlayed on the video with picamera :
 http://mypidrone.com/2016/09/08/overlaying-telemetry-text-on-video-before-wifibroadcast/
Question : 
Is it possible to add feature for SIDE-by-SIDE to set the profile of the glasses like  in "Magic VR Player" android application ?
If that is not possible I will have to use gstreamer plugins VR on a linux PC before sending video but is more complicated.
rx (PC)  ---> gstreamer VR plugins (PC)  --> UDP broadcast (PC) --> myMediaCodecPlayer-for-FPV (Android)
https://www.collabora.com/about-us/blog/2016/07/04/introducing-gstreamer-vr-plug-ins-and-sphvr/
Thanks.

**Comment by Consti10** [comment]
Hello,
It is unclear to me what you mean with "profile like magic vr  Player". This player and its advancement FPV_VR supports both vr and normal video side-by-side, and you can disable side-by-side too.

**Comment by Consti10** [comment]
check out https://github.com/Consti10/FPV_VR_2018
