### ISSUE TITLE
How this feature works "Receive from raw h.264 file" ?

### ISSUE THREAD

**Issue by PhilippeLC92** [Consti10/myMediaCodecPlayer-for-FPV#2]
Hello,
I tested "Receive from UDP Port 5000" with  success :
Command PC Linux :
 ./rx -p $PORT -b $BLOCK_SIZE -r $FECS -f $PACKET_LENGTH $WLAN |socat -b 1024 - UDP4-SENDTO:192.168.43.1:5000
But I do not understand how this feature works "Receive from raw h.264 file" ?
Could explain this feature ?
Thanks.

**Comment by Consti10** [comment]
Hello,
sry for the late answer I've started working on this project recently again.
You can put a raw .h264 file in the "intern storage" folder and play it with the decoder. The main reason was to have a way of testing whether your hw decoder is working or not without the need for an udp stream.
